# Config file for hyperparameter definition
train: true
learning_rate: 0.0003
epochs: 2500
logs: 'inbreast_exp1'
device: 'cuda'
val_interval: 5
data_dir: 'D:\Users\kkouko0\DATASETS\INBreast\INbreast Release 1.0\'
data_dir_virtual: 'D:\Users\kkouko0\DATASETS\HuggingFace'
dataset: Dataset
cross_val_split: [0.6, 0.15, 0.25]
use_seed: True
seed: 0
save_model_when: 0.85 # Metric has to be greater than this value for the model to be saved
cache_rate: 1
use_virtual_data: False

# Dataloader
dataloader:
  batch_size: 20
  num_workers: 2
  shuffle: true

# Optimizer
optimizer: 
  name: 'Adam'
  learning_rate: 0.0003
  betas: [0.9, 0.999]
  epsilon: 0.00000008
  weight_decay: 0

# Learning rate scheduler
scheduler:
  name: 'CosineAnnealingWarmRestarts'
  T_0: 100
  eta_min: 1e-5 

# Loss function
loss:
  name: 'DiceLoss'
  include_background: true
  softmax: true
# Metric 
metric:
  name: 'DiceMetric'
  include_background: False
  reduction: 'mean'

model:
  name: 'UNet'
  spatial_dims: 2
  in_channels: 1
  out_channels: 2
  kernel_size: 3
  up_kernel_size: 3
  channels: [32, 64, 128, 256, 512, 1024]
  strides: [2, 2, 2, 2, 2]
  num_res_units: 3
  dropout: 0.5
  norm: 'instance'

# Train transformations
train_transforms:
  LoadImaged_im:
      keys: ['image']
      ensure_channel_first: True
  LoadImaged_seg:
      keys: ['mask']
      ensure_channel_first: True
  Transposed:
      keys: ['image']
      indices: [0, 2, 1]
  WindowindINBreastImageBasedOnPercentiled:
      keys: ['image']
  Resized_im:
      keys: ['image']
    #   spatial_size: [1024, 1024]
      spatial_size: [2048, 2048]
  Resized_seg:
      keys: ['mask']
    #   spatial_size: [1024, 1024]
      spatial_size: [2048, 2048]
      mode: 'nearest'
  CropForegroundd:
      keys: ['image', 'mask']
      source_key: 'image'
  SpatialPadd:
      keys: ['image', 'mask']
      spatial_size: [1024, 512] 
  ConvertINBreastLesionToMultiChannelMaskd:
      keys: ['mask'] 
  RandCropByLabelClassesd:
      keys: ['image', 'mask', 'segmentation']
      label_key: 'mask'
      spatial_size: [512, 512]
      num_classes: 2
      ratios: [0, 1]
      num_samples: 1
  RandFlipd_x:
      keys: ['image', 'mask', 'segmentation']
      prob: 0
      spatial_axis: 0
  RandFlipd_y:
      keys: ['image', 'mask', 'segmentation']
      prob: 0
      spatial_axis: 1
  RandShiftIntensityd:
      keys: ['image']
      offsets: 0.1
      prob: 0
  RandAdjustContrastd:
      keys: ['image']
      prob: 0
      gamma: [0.95, 1.5]
  ToTensord:
      keys: ['image', 'mask', 'segmentation']

# Validation transformations
eval_transforms:
  LoadImaged_im:
      keys: ['image']
      ensure_channel_first: True
  LoadImaged_seg:
      keys: ['mask']
      ensure_channel_first: True
  Transposed:
      keys: ['image']
      indices: [0, 2, 1]
  WindowindINBreastImageBasedOnPercentiled:
      keys: ['image']
  Resized_im:
      keys: ['image']
    #   spatial_size: [1024, 1024]
      spatial_size: [2048, 2048]
  Resized_seg:
      keys: ['mask']
    #   spatial_size: [1024, 1024]
      spatial_size: [2048, 2048]
      mode: 'nearest'
  CropForegroundd:
      keys: ['image', 'mask']
      source_key: 'image'
  SpatialPadd:
      keys: ['image', 'mask']
      spatial_size: [1024, 512] 
  ConvertINBreastLesionToMultiChannelMaskd:
      keys: ['mask'] 
  RandCropByLabelClassesd:
      keys: ['image', 'mask', 'segmentation']
      label_key: 'mask'
      spatial_size: [512, 512]
      num_classes: 2
      ratios: [0, 1]
      num_samples: 1
  ToTensord:
      keys: ['image', 'mask', 'segmentation']

# Post prediction transformations
post_pred_transforms:
  EnsureType:
  AsDiscrete:
      argmax: True
      to_onehot: 2
      num_classes: 2

# Train transformations for virtual data
train_transforms_virtual:
  LoadMSynthImaged:
      keys: ['image']
  LoadMSynthMaskd:
      keys: ['mask']
  Transposed:
      keys: ['image', 'mask']
      indices: [0, 2, 1]
  WindowMSynthImaged:
      keys: ['image']
  ConvertMSynthLesionToMultiChannelMaskd:
      keys: ['mask']
  RandCropByLabelClassesd:
      keys: ['image', 'mask', 'segmentation']
      label_key: 'mask'
      spatial_size: [512, 512]
      num_classes: 2
      ratios: [0, 1]
      num_samples: 1
  ToTensord:
      keys: ['image', 'mask', 'segmentation']